lib/euclid/web/router.ex
defmodule Euclid.Web.Router do
  use Euclid.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Euclid.Auth.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Euclid.Web do
    pipe_through [:browser, :with_session]

    get "/", PageController, :index

    resources "/users", UserController, only: [:show]

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
  end

  scope "/auth", Euclid.Web do
    pipe_through [:browser, :with_session]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
  end
end

lib/euclid/web/controllers/page_controller.ex
defmodule Euclid.Web.PageController do
  use Euclid.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/euclid/web/controllers/registration_controller.ex
defmodule Euclid.Web.RegistrationController do
  use Euclid.Web, :controller

  alias Euclid.Auth
  alias Euclid.Auth.User

  def new(conn, _params, changeset \\ Auth.change_user(%User{})) do
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => params}) do
    case Auth.create_user(params) do
      {:ok, user} ->
        conn
        |> Guardian.Plug.sign_in(user)
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        new(conn, %{}, changeset)
    end
  end
end

lib/euclid/web/controllers/session_controller.ex
defmodule Euclid.Web.SessionController do
  use Euclid.Web, :controller

  alias Euclid.Auth
  alias Euclid.Auth.Login

  def new(conn, _params, changeset \\ Auth.change_login(%Login{})) do
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"login" => login_params} = params) do
    case Auth.authenticate(login_params) do
      {:ok, user} ->
        conn
        |> Guardian.Plug.sign_in(user)
        |> redirect(to: Map.get(params, "next", page_path(conn, :index)))
      {:error, changeset} ->
        conn
        |> new(%{}, %{changeset | action: :insert})
    end
  end

  def delete(conn, _params) do
    Guardian.Plug.sign_out(conn)
    |> redirect(to: page_path(conn, :index))
  end
end

lib/euclid/web/controllers/user_controller.ex
defmodule Euclid.Web.UserController do
  use Euclid.Web, :controller

  alias Euclid.Auth.User

  plug Guardian.Plug.EnsureAuthenticated, handler: Euclid.Web.AuthErrorHandler

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end
end

lib/euclid/web/views/error_view.ex
defmodule Euclid.Web.ErrorView do
  use Euclid.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/euclid/web/views/layout_view.ex
defmodule Euclid.Web.LayoutView do
  use Euclid.Web, :view
end

lib/euclid/web/views/page_view.ex
defmodule Euclid.Web.PageView do
  use Euclid.Web, :view
end

lib/euclid/web/views/registration_view.ex
defmodule Euclid.Web.RegistrationView do
  use Euclid.Web, :view
end

lib/euclid/web/views/session_view.ex
defmodule Euclid.Web.SessionView do
  use Euclid.Web, :view
end

lib/euclid/web/views/user_view.ex
defmodule Euclid.Web.UserView do
  use Euclid.Web, :view
end

lib/euclid/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Euclid!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @current_user do %>
              <li>
                <%= link @current_user.name, to: user_path(@conn, :show, @current_user.id) %>
              </li>
              <li>
                <%= link "Sign out", to: session_path(@conn, :delete) %>
             </li>
           <% else %>
             <li><%= link "Register", to: registration_path(@conn, :new) %></li>
             <li><%= link "Sign in", to: session_path(@conn, :new) %></li>
           <% end %>
          </ul>
        </nav>
        <a href="<%= page_path(@conn, :index) %>">
          <span class="logo"></span>
        </a>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/euclid/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/euclid/web/templates/session/new.html.eex
<h1>Login</h1>
<%= form_for @changeset, "", [as: :login], fn f -> %>
  <%= error_tag f, :base %>

  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email",
                              class: "form-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password",
                                     class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Login", class: "btn btn-primary" %>
<% end %>

lib/euclid/web/templates/user/show.html.eex
<h1><%= @user.name %></h1>
<code><%= @user.email %></code>